name: Tagging

on:
  push:
    branches: 
        - main

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch
          use_github_release_notes: true
          release_name: "Release <RELEASE_VERSION>"
          max_commits: 100